// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "heading": string; "subtext": string } };
  export const home: { "heading": string; "subtext": string };
}
